apiVersion: v1
kind: Service
metadata:
  name: {{ include "claw-swarm-panel.fullname" . }}
  labels:
    {{- include "claw-swarm-panel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: server
      protocol: TCP
      name: server
    - port: 80
      targetPort: webui
      protocol: TCP
      name: webui
  selector:
    {{- include "claw-swarm-panel.apiserverSelectorLabels" . | nindent 4 }}
